spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
logging:
  level:
    root: info

request-limits:
  limits:
    getAllMovieInfos:
      - duration: 60
        limit: 10
        precision: 5
        name: movieInfoLimiter
    getMovieInfoById:
      - duration: 60
        limit: 5
        precision: 10
        name: movieInfoByIdLimiter

