spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
logging:
  level:
    root: info

request-limits:
  limits:
    getAllMovieInfos:
      - duration: 120
        limit: 10
        precision: 2
        name: movieInfoLimiter
